# Generated by Django 3.1.1 on 2020-09-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200920_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover',
        ),
    ]
