# Generated by Django 3.1.1 on 2020-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_auto_20200920_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='cover',
            field=models.ImageField(null=True, upload_to='sets', verbose_name='Cover'),
        ),
    ]
